// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.
// Source: shared/web/. Edit there and run `pnpm build`.

"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

  // shared/web/core/selectors.ts
  var SEL = {
    scrollContainer: ".infinite-scroll-component",
    postLink: 'a[href^="/posts/"]',
    postContainer: ".relative[tabindex]",
    nickname: '[data-slot="profile-name-label"] span.truncate',
    profileName: '[data-slot="profile-name"]',
    separator: '[data-slot="separator"]',
    card: '[data-slot="card"]',
    cardItem: '[data-slot="carousel-item"]'
  };

  // shared/web/core/storage-keys.ts
  var STORAGE_KEY = "quiet_lounge_data";
  var FILTER_MODE_KEY = "quiet_lounge_filter_mode";
  var DONT_SHOW_FILTER_HINT_KEY = "quiet_lounge_dont_show_filter_hint";

  // shared/web/core/pages.ts
  function isActivePage() {
    const p = window.location.pathname;
    return p === "/" || p.startsWith("/posts") || p.startsWith("/channels");
  }
  __name(isActivePage, "isActivePage");
  function isBlockButtonPage() {
    const p = window.location.pathname;
    return p.startsWith("/posts") || p.startsWith("/channels");
  }
  __name(isBlockButtonPage, "isBlockButtonPage");

  // shared/web/core/cleanbot.ts
  function isCleanbotFiltered(container) {
    if (!container) return false;
    if (container.querySelector("[data-slot]")) return false;
    const text = container.textContent || "";
    return text.includes("클린봇") && text.includes("감지");
  }
  __name(isCleanbotFiltered, "isCleanbotFiltered");

  // shared/web/core/block-check.ts
  function isBlocked(data, personaId, nickname) {
    if (!data) return false;
    if (personaId && data.blockedUsers && data.blockedUsers[personaId]) return true;
    if (nickname) {
      const users = data.blockedUsers || {};
      for (const key in users) {
        if (users[key].nickname === nickname) return true;
      }
      const nbs = data.nicknameOnlyBlocks || [];
      for (let i = 0; i < nbs.length; i++) {
        if (nbs[i].nickname === nickname) return true;
      }
    }
    return false;
  }
  __name(isBlocked, "isBlocked");

  // shared/web/core/style.ts
  function applyStyle(el, blocked, mode) {
    if (!el) return;
    if (blocked) {
      if (mode === "blur") {
        el.style.filter = "blur(5px)";
        el.style.opacity = "0.3";
        el.style.pointerEvents = "none";
        el.style.display = "";
      } else {
        el.style.display = "none";
        el.style.filter = "";
        el.style.opacity = "";
        el.style.pointerEvents = "";
      }
    } else {
      el.style.display = "";
      el.style.filter = "";
      el.style.opacity = "";
      el.style.pointerEvents = "";
    }
  }
  __name(applyStyle, "applyStyle");

  // shared/web/entries/chrome.ts
  (function() {
    "use strict";
    const QL_PRIMARY = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "#6A86F8" : "#4A6CF7";
    function debounce(fn, delay) {
      let timer;
      return function() {
        clearTimeout(timer);
        timer = setTimeout(fn, delay);
      };
    }
    __name(debounce, "debounce");
    function createEmptyData() {
      return {
        version: 2,
        blockedUsers: {},
        nicknameOnlyBlocks: [],
        personaCache: {}
      };
    }
    __name(createEmptyData, "createEmptyData");
    let blockData = createEmptyData();
    let filterMode = "hide";
    let dontShowFilterHint = false;
    async function loadBlockData() {
      return new Promise((resolve) => {
        chrome.storage.local.get(
          [STORAGE_KEY, FILTER_MODE_KEY, DONT_SHOW_FILTER_HINT_KEY],
          (result) => {
            if (result[STORAGE_KEY]) {
              try {
                blockData = JSON.parse(result[STORAGE_KEY]);
              } catch {
                blockData = createEmptyData();
              }
            }
            if (result[FILTER_MODE_KEY]) {
              filterMode = result[FILTER_MODE_KEY];
            }
            dontShowFilterHint = !!result[DONT_SHOW_FILTER_HINT_KEY];
            resolve();
          }
        );
      });
    }
    __name(loadBlockData, "loadBlockData");
    async function saveBlockData() {
      return new Promise((resolve) => {
        chrome.storage.local.set({ [STORAGE_KEY]: JSON.stringify(blockData) }, resolve);
      });
    }
    __name(saveBlockData, "saveBlockData");
    function isBlocked2(personaId, nickname) {
      return isBlocked(blockData, personaId, nickname);
    }
    __name(isBlocked2, "isBlocked");
    async function blockUser(personaId, nickname) {
      if (personaId) {
        const existing = blockData.blockedUsers[personaId];
        blockData.blockedUsers[personaId] = {
          personaId,
          nickname,
          blockedAt: existing?.blockedAt ?? (/* @__PURE__ */ new Date()).toISOString()
        };
        blockData.nicknameOnlyBlocks = blockData.nicknameOnlyBlocks.filter(
          (b) => b.nickname !== nickname
        );
      } else {
        if (isBlocked2(void 0, nickname)) return;
        blockData.nicknameOnlyBlocks.push({
          nickname,
          blockedAt: (/* @__PURE__ */ new Date()).toISOString()
        });
      }
      await saveBlockData();
    }
    __name(blockUser, "blockUser");
    function qlFilterHintDialog() {
      return new Promise((resolve) => {
        const overlay = document.createElement("div");
        overlay.style.cssText = "position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:999999;display:flex;align-items:center;justify-content:center;";
        const dialog = document.createElement("div");
        dialog.style.cssText = "background:#1a1a1a;color:#e0e0e0;border-radius:14px;padding:20px;max-width:340px;width:90%;font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 24px rgba(0,0,0,0.4);";
        const title = document.createElement("p");
        title.textContent = "팁: 흐림 처리 모드";
        title.style.cssText = "font-size:16px;font-weight:600;margin:0 0 10px;";
        const msg = document.createElement("p");
        msg.textContent = "차단된 글을 완전히 숨기는 대신 흐리게만 처리할 수도 있어요. 익스텐션 팝업의 '흐림 처리' 토글에서 켤 수 있습니다.";
        msg.style.cssText = "font-size:14px;margin:0 0 18px;line-height:1.5;color:#bbb;";
        const btnRow = document.createElement("div");
        btnRow.style.cssText = "display:flex;gap:10px;";
        const dontBtn = document.createElement("button");
        dontBtn.textContent = "다시 보지 않기";
        dontBtn.style.cssText = "flex:1;padding:10px;border:1px solid #444;background:transparent;color:#aaa;border-radius:8px;font-size:13px;cursor:pointer;";
        const okBtn = document.createElement("button");
        okBtn.textContent = "확인";
        okBtn.style.cssText = "flex:1;padding:10px;border:none;background:#4A6CF7;color:#fff;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;";
        function close(result) {
          overlay.remove();
          resolve(result);
        }
        __name(close, "close");
        dontBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          close("dontShow");
        });
        okBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          close("confirm");
        });
        overlay.addEventListener("click", (e) => {
          if (e.target === overlay) close("confirm");
        });
        btnRow.appendChild(dontBtn);
        btnRow.appendChild(okBtn);
        dialog.appendChild(title);
        dialog.appendChild(msg);
        dialog.appendChild(btnRow);
        overlay.appendChild(dialog);
        document.body.appendChild(overlay);
      });
    }
    __name(qlFilterHintDialog, "qlFilterHintDialog");
    async function maybeShowFilterModeHint() {
      if (filterMode === "blur") return;
      if (dontShowFilterHint) return;
      const result = await qlFilterHintDialog();
      if (result === "dontShow") {
        dontShowFilterHint = true;
        await new Promise((resolve) => {
          chrome.storage.local.set({ [DONT_SHOW_FILTER_HINT_KEY]: true }, resolve);
        });
      }
    }
    __name(maybeShowFilterModeHint, "maybeShowFilterModeHint");
    const personaMap = /* @__PURE__ */ new Map();
    const personaCache = /* @__PURE__ */ new Map();
    function installApiInterceptor() {
      window.addEventListener("message", (event) => {
        if (event.data?.type !== "QUIET_LOUNGE_API_DATA") return;
        const mapData = event.data.personaMap;
        const cacheData = event.data.personaCache;
        if (mapData && typeof mapData === "object") {
          for (const [postId, personaId] of Object.entries(mapData)) {
            personaMap.set(postId, personaId);
          }
        }
        if (cacheData && typeof cacheData === "object") {
          for (const [personaId, nickname] of Object.entries(cacheData)) {
            personaCache.set(personaId, { nickname });
          }
        }
        filterAll();
        autoPromoteBlocks();
      });
      window.postMessage({ type: "QUIET_LOUNGE_REQUEST_DATA" }, "*");
    }
    __name(installApiInterceptor, "installApiInterceptor");
    async function autoPromoteBlocks() {
      let changed = false;
      for (const [pid, { nickname }] of personaCache) {
        const idx = blockData.nicknameOnlyBlocks.findIndex((b) => b.nickname === nickname);
        if (idx !== -1) {
          const block = blockData.nicknameOnlyBlocks.splice(idx, 1)[0];
          blockData.blockedUsers[pid] = {
            personaId: pid,
            nickname,
            blockedAt: block.blockedAt
          };
          changed = true;
        }
        if (blockData.blockedUsers[pid] && blockData.blockedUsers[pid].nickname !== nickname) {
          blockData.blockedUsers[pid].nickname = nickname;
          changed = true;
        }
      }
      if (changed) await saveBlockData();
    }
    __name(autoPromoteBlocks, "autoPromoteBlocks");
    function applyBlockStyle(el) {
      applyStyle(el, true, filterMode);
    }
    __name(applyBlockStyle, "applyBlockStyle");
    function clearBlockStyle(el) {
      applyStyle(el, false, filterMode);
    }
    __name(clearBlockStyle, "clearBlockStyle");
    let totalBlocked = 0;
    function filterAll() {
      if (!isActivePage()) return;
      totalBlocked = 0;
      filterFeedPosts();
      filterCarouselCards();
      updateBadge();
    }
    __name(filterAll, "filterAll");
    function filterFeedPosts() {
      const postLinks = document.querySelectorAll(SEL.postLink);
      postLinks.forEach((link) => {
        const postId = link.getAttribute("href")?.replace("/posts/", "");
        const nicknameEl = link.querySelector(SEL.nickname);
        const nickname = nicknameEl?.textContent?.trim();
        if (!postId && !nickname) return;
        const pid = postId ? personaMap.get(postId) : void 0;
        const blocked = isBlocked2(pid, nickname);
        const container = link.closest(SEL.postContainer) || link.parentElement?.parentElement;
        if (!container) return;
        if (blocked) {
          totalBlocked++;
          applyBlockStyle(container);
          const wrapper = container.parentElement;
          const separator = wrapper?.nextElementSibling;
          if (separator?.getAttribute?.("data-slot") === "separator") {
            applyBlockStyle(separator);
          }
        } else {
          clearBlockStyle(container);
          const wrapper = container.parentElement;
          const separator = wrapper?.nextElementSibling;
          if (separator?.getAttribute?.("data-slot") === "separator") {
            clearBlockStyle(separator);
          }
        }
      });
    }
    __name(filterFeedPosts, "filterFeedPosts");
    function filterCarouselCards() {
      const cards = document.querySelectorAll(SEL.card);
      cards.forEach((card) => {
        const nickname = card.querySelector(SEL.nickname)?.textContent?.trim();
        if (!nickname) return;
        const blocked = isBlocked2(void 0, nickname);
        const item = card.closest(SEL.cardItem);
        if (!item) return;
        if (blocked) {
          totalBlocked++;
          applyBlockStyle(item);
        } else {
          clearBlockStyle(item);
        }
      });
    }
    __name(filterCarouselCards, "filterCarouselCards");
    function updateBadge() {
      chrome.runtime.sendMessage({
        type: "UPDATE_BADGE",
        count: totalBlocked
      });
    }
    __name(updateBadge, "updateBadge");
    function findPersonaId(container) {
      let pid;
      const profileLink = container.querySelector('a[href^="/profiles/"]');
      if (profileLink) {
        pid = profileLink.getAttribute("href")?.replace("/profiles/", "");
      }
      if (!pid) {
        const postLink = container.closest('a[href^="/posts/"]') || container.querySelector('a[href^="/posts/"]') || container.closest(".relative[tabindex]")?.querySelector('a[href^="/posts/"]');
        if (postLink) {
          const postId = postLink.getAttribute("href")?.replace("/posts/", "");
          if (postId) pid = personaMap.get(postId);
        }
      }
      if (!pid) {
        const pathMatch = window.location.pathname.match(/^\/posts\/([^/]+)/);
        if (pathMatch) pid = personaMap.get(pathMatch[1]);
      }
      return pid;
    }
    __name(findPersonaId, "findPersonaId");
    function createBlockBtn() {
      const btn = document.createElement("button");
      btn.className = "quiet-lounge-btn";
      btn.textContent = "✕";
      btn.title = "이 유저 차단";
      btn.style.cssText = "margin-left:6px;cursor:pointer;opacity:0.6;font-size:12px;border:1px solid rgba(255,80,80,0.3);background:rgba(255,80,80,0.08);padding:1px 5px;line-height:1.2;color:#ff5050;border-radius:4px;vertical-align:middle;transition:all 0.15s;position:relative;z-index:10;";
      btn.addEventListener("mouseenter", () => {
        btn.style.opacity = "1";
        btn.style.background = "rgba(255,80,80,0.2)";
        btn.style.borderColor = "rgba(255,80,80,0.6)";
      });
      btn.addEventListener("mouseleave", () => {
        btn.style.opacity = "0.6";
        btn.style.background = "rgba(255,80,80,0.08)";
        btn.style.borderColor = "rgba(255,80,80,0.3)";
      });
      btn.addEventListener(
        "mousedown",
        (e) => {
          e.preventDefault();
          e.stopPropagation();
          e.stopImmediatePropagation();
        },
        true
      );
      btn.addEventListener(
        "pointerdown",
        (e) => {
          e.stopPropagation();
          e.stopImmediatePropagation();
        },
        true
      );
      return btn;
    }
    __name(createBlockBtn, "createBlockBtn");
    function injectBlockButtons() {
      if (!isBlockButtonPage()) return;
      document.querySelectorAll(SEL.profileName).forEach((el) => {
        if (el.querySelector(".quiet-lounge-btn")) return;
        if (isCleanbotFiltered(el.closest(SEL.postContainer) || el.closest(SEL.postLink))) return;
        const btn = createBlockBtn();
        btn.addEventListener("click", async (e) => {
          e.preventDefault();
          e.stopPropagation();
          e.stopImmediatePropagation();
          const nickname = el.querySelector('[data-slot="profile-name-label"] span.truncate')?.textContent?.trim();
          if (!nickname) return;
          const pid = findPersonaId(el);
          if (confirm(`"${nickname}" 유저를 차단하시겠습니까?`)) {
            await blockUser(pid, nickname);
            filterAll();
            injectBlockButtons();
            await maybeShowFilterModeHint();
          }
        });
        el.appendChild(btn);
      });
      document.querySelectorAll(SEL.postContainer).forEach((container) => {
        if (container.querySelector(".quiet-lounge-btn")) return;
        if (container.querySelector(SEL.profileName)) return;
        if (isCleanbotFiltered(container)) return;
        const postLink = container.querySelector(SEL.postLink) || container.closest(SEL.postLink);
        if (!postLink) return;
        const btn = createBlockBtn();
        btn.addEventListener("click", async (e) => {
          e.preventDefault();
          e.stopPropagation();
          e.stopImmediatePropagation();
          const pid = findPersonaId(container);
          const nickname = pid ? personaCache.get(pid) : null;
          if (!pid) {
            alert("personaId를 찾을 수 없습니다. 글 상세 페이지에서 차단해주세요.");
            return;
          }
          if (confirm(`"${nickname || pid}" 유저를 차단하시겠습니까?`)) {
            await blockUser(pid, nickname || "");
            filterAll();
            injectBlockButtons();
            await maybeShowFilterModeHint();
          }
        });
        const firstRow = container.querySelector("a > div");
        if (firstRow) {
          firstRow.appendChild(btn);
        } else {
          container.appendChild(btn);
        }
      });
    }
    __name(injectBlockButtons, "injectBlockButtons");
    let lastPath = window.location.pathname;
    function watchNavigation() {
      window.addEventListener("popstate", onNavigate);
      const origPushState = history.pushState;
      history.pushState = function(...args) {
        origPushState.apply(this, args);
        onNavigate();
      };
      const origReplaceState = history.replaceState;
      history.replaceState = function(...args) {
        origReplaceState.apply(this, args);
        onNavigate();
      };
    }
    __name(watchNavigation, "watchNavigation");
    function onNavigate() {
      const newPath = window.location.pathname;
      if (newPath === lastPath) return;
      lastPath = newPath;
      profileStatsCache = { personaId: null, stats: null, monthlyPosts: null, monthlyComments: null };
      stopProfileStatsGuard();
      if (isActivePage()) {
        setTimeout(() => {
          filterAll();
          injectBlockButtons();
        }, 500);
      }
      if (isProfilePage()) {
        setTimeout(() => injectProfileStats(), 500);
      }
    }
    __name(onNavigate, "onNavigate");
    chrome.storage.onChanged.addListener((changes) => {
      if (changes[STORAGE_KEY]) {
        try {
          blockData = JSON.parse(changes[STORAGE_KEY].newValue);
        } catch {
          blockData = createEmptyData();
        }
        filterAll();
      }
      if (changes[FILTER_MODE_KEY]) {
        filterMode = changes[FILTER_MODE_KEY].newValue || "hide";
        filterAll();
      }
      if (changes[DONT_SHOW_FILTER_HINT_KEY]) {
        dontShowFilterHint = !!changes[DONT_SHOW_FILTER_HINT_KEY].newValue;
      }
    });
    function isProfilePage() {
      return window.location.pathname.startsWith("/profiles/");
    }
    __name(isProfilePage, "isProfilePage");
    function getProfilePersonaId() {
      const match = window.location.pathname.match(/^\/profiles\/([^/?]+)/);
      return match ? match[1] : null;
    }
    __name(getProfilePersonaId, "getProfilePersonaId");
    async function fetchPersonaStats(personaId) {
      try {
        const resp = await fetch(`https://api.lounge.naver.com/user-api/v1/personas/${personaId}`, {
          credentials: "include"
        });
        if (!resp.ok) return null;
        const json = await resp.json();
        return json.data;
      } catch {
        return null;
      }
    }
    __name(fetchPersonaStats, "fetchPersonaStats");
    async function fetchMonthlyCount(personaId, type) {
      const now = /* @__PURE__ */ new Date();
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
      let count = 0;
      let cursor = "";
      const isComments = type === "comments";
      for (let page = 0; page < 50; page++) {
        try {
          const actUrl = `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/${type}?limit=100${cursor ? `&cursor=${cursor}` : ""}`;
          const actResp = await fetch(actUrl, { credentials: "include" });
          if (!actResp.ok) break;
          const actJson = await actResp.json();
          const items = actJson.data?.items || [];
          if (items.length === 0) break;
          let hasThisMonth = false;
          if (isComments) {
            const ids = items.map((item) => item.commentId);
            const params = ids.map((id) => `commentNoList=${id}`).join("&");
            const detailResp = await fetch(
              `https://api.lounge.naver.com/content-api/v1/comments?${params}`,
              { credentials: "include" }
            );
            if (!detailResp.ok) break;
            const detailJson = await detailResp.json();
            const raw = detailJson.data?.rawResponse;
            const parsed = raw ? JSON.parse(raw) : null;
            const commentList = parsed?.result?.commentList || [];
            for (const comment of commentList) {
              const dateStr = comment.regTimeGmt || "";
              if (dateStr && new Date(dateStr) >= monthStart) {
                count++;
                hasThisMonth = true;
              }
            }
          } else {
            const ids = items.map((item) => item.postId);
            const params = ids.map((id) => `postIds=${id}`).join("&");
            const detailResp = await fetch(
              `https://api.lounge.naver.com/content-api/v1/posts?${params}`,
              { credentials: "include" }
            );
            if (!detailResp.ok) break;
            const detailJson = await detailResp.json();
            const details = Array.isArray(detailJson.data) ? detailJson.data : [];
            for (const item of details) {
              const dateStr = item.createTime || "";
              if (dateStr && new Date(dateStr) >= monthStart) {
                count++;
                hasThisMonth = true;
              }
            }
          }
          if (!hasThisMonth) break;
          if (!actJson.data?.cursorInfo?.hasNext) break;
          cursor = actJson.data?.cursorInfo?.endCursor || "";
          if (!cursor) break;
        } catch {
          break;
        }
      }
      return count;
    }
    __name(fetchMonthlyCount, "fetchMonthlyCount");
    let profileStatsCache = {
      personaId: null,
      stats: null,
      monthlyPosts: null,
      monthlyComments: null
    };
    let profileStatsRafId = null;
    function buildProfileStatsHtml() {
      const stats = profileStatsCache.stats;
      const totalPosts = stats.totalPostCount || 0;
      const totalComments = stats.totalCommentCount || 0;
      const mp = profileStatsCache.monthlyPosts;
      const mc = profileStatsCache.monthlyComments;
      const spinner = `<span style="display:inline-block;width:14px;height:14px;border:2px solid rgba(255,255,255,0.2);border-top-color:${QL_PRIMARY};border-radius:50%;animation:ql-spin 0.8s linear infinite;vertical-align:middle;"></span>`;
      const monthlyPostsText = mp !== null ? mp : spinner;
      const monthlyCommentsText = mc !== null ? mc : spinner;
      return `<div style="font-weight:600;font-size:14px;margin-bottom:10px;color:${QL_PRIMARY};">활동 통계</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${totalPosts}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">총 작성글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${totalComments}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">총 댓글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${monthlyPostsText}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">이번달 작성글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${monthlyCommentsText}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">이번달 댓글</div></div></div>`;
    }
    __name(buildProfileStatsHtml, "buildProfileStatsHtml");
    if (!document.getElementById("ql-spinner-style")) {
      const style = document.createElement("style");
      style.id = "ql-spinner-style";
      style.textContent = "@keyframes ql-spin { to { transform: rotate(360deg); } }";
      document.head.appendChild(style);
    }
    function insertProfileStatsBox() {
      if (document.getElementById("ql-profile-stats")) return;
      const tabsEl = document.querySelector('[data-slot="tabs"]');
      if (!tabsEl) return;
      const box = document.createElement("div");
      box.id = "ql-profile-stats";
      box.style.cssText = "margin:12px 20px 0;padding:14px 16px;background:rgba(74,108,247,0.08);border:1px solid rgba(74,108,247,0.2);border-radius:10px;font-size:13px;color:var(--color-neutral-foreground-default,#e0e0e0);";
      box.innerHTML = buildProfileStatsHtml();
      tabsEl.before(box);
    }
    __name(insertProfileStatsBox, "insertProfileStatsBox");
    let profileStatsObserver = null;
    function startProfileStatsGuard() {
      stopProfileStatsGuard();
      const startTime = Date.now();
      function tick() {
        if (!isProfilePage() || !profileStatsCache.stats) {
          profileStatsRafId = null;
          return;
        }
        insertProfileStatsBox();
        if (Date.now() - startTime < 3e3) {
          profileStatsRafId = requestAnimationFrame(tick);
        } else {
          profileStatsRafId = null;
          profileStatsObserver = new MutationObserver(
            debounce(() => {
              if (isProfilePage() && profileStatsCache.stats) {
                insertProfileStatsBox();
              }
            }, 100)
          );
          profileStatsObserver.observe(document.body, { childList: true, subtree: true });
        }
      }
      __name(tick, "tick");
      profileStatsRafId = requestAnimationFrame(tick);
    }
    __name(startProfileStatsGuard, "startProfileStatsGuard");
    function stopProfileStatsGuard() {
      if (profileStatsRafId) {
        cancelAnimationFrame(profileStatsRafId);
        profileStatsRafId = null;
      }
      if (profileStatsObserver) {
        profileStatsObserver.disconnect();
        profileStatsObserver = null;
      }
    }
    __name(stopProfileStatsGuard, "stopProfileStatsGuard");
    function injectProfileStats() {
      if (!isProfilePage()) return;
      const personaId = getProfilePersonaId();
      if (!personaId) return;
      if (profileStatsCache.personaId === personaId && profileStatsCache.stats) {
        startProfileStatsGuard();
        return;
      }
      fetchPersonaStats(personaId).then((stats) => {
        if (!stats) return;
        if (stats.isOwner) {
          chrome.storage.local.set({ quiet_lounge_my_persona_id: personaId });
        }
        profileStatsCache = { personaId, stats, monthlyPosts: null, monthlyComments: null };
        const now = /* @__PURE__ */ new Date();
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
        const createTime = stats.createTime ? new Date(stats.createTime) : null;
        const createdThisMonth = createTime && createTime >= monthStart;
        if (createdThisMonth) {
          profileStatsCache.monthlyPosts = stats.totalPostCount || 0;
          profileStatsCache.monthlyComments = stats.totalCommentCount || 0;
        } else {
          fetchMonthlyCount(personaId, "posts").then((count) => {
            profileStatsCache.monthlyPosts = count;
            const el = document.getElementById("ql-profile-stats");
            if (el) el.innerHTML = buildProfileStatsHtml();
          });
          fetchMonthlyCount(personaId, "comments").then((count) => {
            profileStatsCache.monthlyComments = count;
            const el = document.getElementById("ql-profile-stats");
            if (el) el.innerHTML = buildProfileStatsHtml();
          });
        }
        startProfileStatsGuard();
      });
    }
    __name(injectProfileStats, "injectProfileStats");
    function saveMyStats(statsObj) {
      chrome.storage.local.set({
        quiet_lounge_my_stats: JSON.stringify(statsObj)
      });
    }
    __name(saveMyStats, "saveMyStats");
    async function fetchAndStoreMyStats() {
      try {
        const meResp = await fetch("https://api.lounge.naver.com/user-api/v1/members/me/personas", {
          credentials: "include"
        });
        if (!meResp.ok) {
          chrome.storage.local.remove("quiet_lounge_my_stats");
          return;
        }
        const meJson = await meResp.json();
        const meData = Array.isArray(meJson.data) ? meJson.data[0] : meJson.data;
        if (!meData?.personaId) return;
        const personaId = meData.personaId;
        chrome.storage.local.set({ quiet_lounge_my_persona_id: personaId });
        let totalPosts = 0;
        let totalComments = 0;
        let nickname = meData.nickname || "";
        let createTime = meData.createTime ? new Date(meData.createTime) : null;
        try {
          const statsResp = await fetch(
            `https://api.lounge.naver.com/user-api/v1/personas/${personaId}`,
            { credentials: "include" }
          );
          if (statsResp.ok) {
            const statsJson = await statsResp.json();
            const sData = statsJson.data;
            if (sData) {
              totalPosts = sData.totalPostCount || 0;
              totalComments = sData.totalCommentCount || 0;
              nickname = sData.nickname || nickname;
              createTime = sData.createTime ? new Date(sData.createTime) : createTime;
            }
          }
        } catch {
          try {
            const postsResp = await fetch(
              `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/posts?limit=1`,
              { credentials: "include" }
            );
            if (postsResp.ok) {
              const pJson = await postsResp.json();
              totalPosts = pJson.data?.totalPostCount || 0;
            }
            const commentsResp = await fetch(
              `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/comments?limit=1`,
              { credentials: "include" }
            );
            if (commentsResp.ok) {
              const cJson = await commentsResp.json();
              totalComments = cJson.data?.totalCommentCount || cJson.data?.totalCount || 0;
            }
          } catch {
          }
        }
        const now = /* @__PURE__ */ new Date();
        const stats = {
          personaId,
          nickname,
          totalPosts,
          totalComments,
          monthlyPosts: "...",
          monthlyComments: "...",
          updatedAt: now.toISOString()
        };
        saveMyStats(stats);
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
        const createdThisMonth = createTime && createTime >= monthStart;
        if (createdThisMonth) {
          stats.monthlyPosts = totalPosts;
          stats.monthlyComments = totalComments;
          saveMyStats(stats);
        } else {
          fetchMonthlyCount(personaId, "posts").then((count) => {
            stats.monthlyPosts = count;
          }).catch(() => {
            stats.monthlyPosts = "?";
          }).finally(() => saveMyStats(stats));
          fetchMonthlyCount(personaId, "comments").then((count) => {
            stats.monthlyComments = count;
          }).catch(() => {
            stats.monthlyComments = "?";
          }).finally(() => saveMyStats(stats));
        }
      } catch {
      }
    }
    __name(fetchAndStoreMyStats, "fetchAndStoreMyStats");
    chrome.runtime.onMessage.addListener((message) => {
      if (message.type === "REFRESH_MY_STATS") {
        fetchAndStoreMyStats();
      }
    });
    async function init() {
      await loadBlockData();
      fetchAndStoreMyStats();
      installApiInterceptor();
      watchNavigation();
      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", start);
      } else {
        start();
      }
    }
    __name(init, "init");
    function start() {
      if (isActivePage()) {
        filterAll();
        injectBlockButtons();
      }
      injectProfileStats();
      const target = document.querySelector(SEL.scrollContainer) || document.body;
      const debouncedUpdate = debounce(() => {
        if (isActivePage()) {
          filterAll();
          injectBlockButtons();
        }
        injectProfileStats();
      }, 200);
      const observer = new MutationObserver(debouncedUpdate);
      observer.observe(target, { childList: true, subtree: true });
    }
    __name(start, "start");
    init();
  })();
})();
