// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.
// Source: shared/web/. Edit there and run `pnpm build`.

"use strict";
(() => {
  // shared/web/entries/safari-injector.ts
  (function() {
    "use strict";
    const script = document.createElement("script");
    script.src = (typeof browser !== "undefined" ? browser : chrome).runtime.getURL(
      "content-scripts/api-interceptor.js"
    );
    document.documentElement.appendChild(script);
    script.onload = function() {
      script.remove();
    };
  })();
})();
