// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.
// Source: shared/web/. Edit there and run `pnpm build`.

"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

  // shared/web/core/selectors.ts
  var SEL = {
    scrollContainer: ".infinite-scroll-component",
    postLink: 'a[href^="/posts/"]',
    postContainer: ".relative[tabindex]",
    nickname: '[data-slot="profile-name-label"] span.truncate',
    profileName: '[data-slot="profile-name"]',
    separator: '[data-slot="separator"]',
    card: '[data-slot="card"]',
    cardItem: '[data-slot="carousel-item"]'
  };

  // shared/web/core/storage-keys.ts
  var STORAGE_KEY = "quiet_lounge_data";
  var FILTER_MODE_KEY = "quiet_lounge_filter_mode";
  var DONT_SHOW_FILTER_HINT_KEY = "quiet_lounge_dont_show_filter_hint";

  // shared/web/core/pages.ts
  function isActivePage() {
    const p = window.location.pathname;
    return p === "/" || p.startsWith("/posts") || p.startsWith("/channels");
  }
  __name(isActivePage, "isActivePage");
  function isBlockButtonPage() {
    const p = window.location.pathname;
    return p.startsWith("/posts") || p.startsWith("/channels");
  }
  __name(isBlockButtonPage, "isBlockButtonPage");

  // shared/web/core/block-check.ts
  function isBlocked(data, personaId, nickname) {
    if (!data) return false;
    if (personaId && data.blockedUsers && data.blockedUsers[personaId]) return true;
    if (nickname) {
      const users = data.blockedUsers || {};
      for (const key in users) {
        if (users[key].nickname === nickname) return true;
      }
      const nbs = data.nicknameOnlyBlocks || [];
      for (let i = 0; i < nbs.length; i++) {
        if (nbs[i].nickname === nickname) return true;
      }
    }
    return false;
  }
  __name(isBlocked, "isBlocked");

  // shared/web/core/style.ts
  function applyStyle(el, blocked, mode) {
    if (!el) return;
    if (blocked) {
      if (mode === "blur") {
        el.style.filter = "blur(5px)";
        el.style.opacity = "0.3";
        el.style.pointerEvents = "none";
        el.style.display = "";
      } else {
        el.style.display = "none";
        el.style.filter = "";
        el.style.opacity = "";
        el.style.pointerEvents = "";
      }
    } else {
      el.style.display = "";
      el.style.filter = "";
      el.style.opacity = "";
      el.style.pointerEvents = "";
    }
  }
  __name(applyStyle, "applyStyle");

  // shared/web/core/filter-engine.ts
  function runFilterPass(ctx) {
    return filterFeedPosts(ctx) + filterCarouselCards(ctx);
  }
  __name(runFilterPass, "runFilterPass");
  function filterFeedPosts(ctx) {
    let blocked = 0;
    document.querySelectorAll(SEL.postLink).forEach((link) => {
      const postId = link.getAttribute("href")?.replace("/posts/", "") || void 0;
      const nicknameRaw = link.querySelector(SEL.nickname)?.textContent;
      const nickname = nicknameRaw?.trim() || void 0;
      if (!postId && !nickname) return;
      const pid = postId ? ctx.personaIdForPost(postId) : void 0;
      const isBlk = isBlocked(ctx.blockData, pid, nickname);
      const container = link.closest(SEL.postContainer) || link.parentElement?.parentElement;
      if (!container) return;
      if (isBlk) blocked++;
      applyStyle(container, isBlk, ctx.filterMode);
      const separator = container.parentElement?.nextElementSibling;
      if (separator && separator.getAttribute?.("data-slot") === "separator") {
        applyStyle(separator, isBlk, ctx.filterMode);
      }
    });
    return blocked;
  }
  __name(filterFeedPosts, "filterFeedPosts");
  function filterCarouselCards(ctx) {
    let blocked = 0;
    document.querySelectorAll(SEL.card).forEach((card) => {
      const nickname = card.querySelector(SEL.nickname)?.textContent?.trim();
      if (!nickname) return;
      const isBlk = isBlocked(ctx.blockData, void 0, nickname);
      const item = card.closest(SEL.cardItem);
      if (!item) return;
      if (isBlk) blocked++;
      applyStyle(item, isBlk, ctx.filterMode);
    });
    return blocked;
  }
  __name(filterCarouselCards, "filterCarouselCards");

  // shared/web/core/cleanbot.ts
  function isCleanbotFiltered(container) {
    if (!container) return false;
    if (container.querySelector("[data-slot]")) return false;
    const text = container.textContent || "";
    return text.includes("클린봇") && text.includes("감지");
  }
  __name(isCleanbotFiltered, "isCleanbotFiltered");

  // shared/web/core/find-persona-id.ts
  function findPersonaId(container, personaIdForPost) {
    const profileLink = container.querySelector('a[href^="/profiles/"]');
    if (profileLink) {
      const href = profileLink.getAttribute("href");
      const pid = href ? href.replace("/profiles/", "") : "";
      if (pid) return pid;
    }
    const postLink = container.closest('a[href^="/posts/"]') || container.querySelector('a[href^="/posts/"]') || container.closest(".relative[tabindex]")?.querySelector('a[href^="/posts/"]');
    if (postLink) {
      const postId = postLink.getAttribute("href")?.replace("/posts/", "");
      return postId ? personaIdForPost(postId) : void 0;
    }
    const pathMatch = window.location.pathname.match(/^\/posts\/([^/]+)/);
    if (pathMatch) {
      const pid = personaIdForPost(pathMatch[1]);
      if (pid) return pid;
    }
    return void 0;
  }
  __name(findPersonaId, "findPersonaId");

  // shared/web/core/inject-buttons.ts
  function injectBlockButtons(adapter, ctx) {
    if (!isBlockButtonPage()) return;
    const btnSelector = "." + adapter.buttonClassName;
    document.querySelectorAll(SEL.profileName).forEach((el) => {
      if (skipExistingButton(el, btnSelector, adapter)) return;
      if (isCleanbotFiltered(el.closest(SEL.postContainer) || el.closest(SEL.postLink))) return;
      const btn = adapter.createButton();
      btn.addEventListener("click", async (e) => {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        const nickname = el.querySelector('[data-slot="profile-name-label"] span.truncate')?.textContent?.trim();
        if (!nickname) return;
        const pid = ctx.findPersonaId(el);
        await adapter.onBlockClick(pid, nickname);
      });
      el.appendChild(btn);
      adapter.onButtonAttached?.(btn);
    });
    document.querySelectorAll(SEL.postContainer).forEach((container) => {
      if (container.querySelector(SEL.profileName)) return;
      if (isCleanbotFiltered(container)) return;
      if (skipExistingButton(container, btnSelector, adapter)) return;
      const postLink = container.querySelector(SEL.postLink) || container.closest(SEL.postLink);
      if (!postLink) return;
      const pid = ctx.findPersonaId(container);
      if (!pid && adapter.pathBMissingPidStrategy === "skip") return;
      const btn = adapter.createButton();
      btn.addEventListener("click", async (e) => {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        const currentPid = ctx.findPersonaId(container);
        if (!currentPid) {
          await adapter.onMissingPersonaId?.();
          return;
        }
        const nickname = ctx.nicknameForPersonaId?.(currentPid) || currentPid;
        await adapter.onBlockClick(currentPid, nickname);
      });
      const firstRow = container.querySelector("a > div");
      if (firstRow) firstRow.appendChild(btn);
      else container.appendChild(btn);
      adapter.onButtonAttached?.(btn);
    });
  }
  __name(injectBlockButtons, "injectBlockButtons");
  function skipExistingButton(container, btnSelector, adapter) {
    const existing = container.querySelector(btnSelector);
    if (!existing) return false;
    if (adapter.shouldSkipExistingButton?.(existing) ?? true) return true;
    existing.remove();
    return false;
  }
  __name(skipExistingButton, "skipExistingButton");

  // shared/web/entries/safari-ext.ts
  (function() {
    "use strict";
    const browser = globalThis.browser || globalThis.chrome;
    const QL_PRIMARY = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "#6A86F8" : "#4A6CF7";
    const QLStorage = typeof globalThis.__QL_storage !== "undefined" && globalThis.__QL_storage._ready ? globalThis.__QL_storage : browser.storage.local;
    function debounce(fn, delay) {
      let timer;
      return function() {
        clearTimeout(timer);
        timer = setTimeout(fn, delay);
      };
    }
    __name(debounce, "debounce");
    function createEmptyData() {
      return {
        version: 2,
        blockedUsers: {},
        nicknameOnlyBlocks: [],
        personaCache: {}
      };
    }
    __name(createEmptyData, "createEmptyData");
    let blockData = createEmptyData();
    let filterMode = "hide";
    let dontShowFilterHint = false;
    async function safariSet(data) {
      try {
        await QLStorage.remove(Object.keys(data));
        await QLStorage.set(data);
      } catch {
      }
    }
    __name(safariSet, "safariSet");
    async function loadBlockData() {
      try {
        const result = await QLStorage.get([STORAGE_KEY, FILTER_MODE_KEY, DONT_SHOW_FILTER_HINT_KEY]);
        if (result[STORAGE_KEY]) {
          blockData = JSON.parse(result[STORAGE_KEY]);
        }
        if (result[FILTER_MODE_KEY]) {
          filterMode = result[FILTER_MODE_KEY];
        }
        dontShowFilterHint = !!result[DONT_SHOW_FILTER_HINT_KEY];
      } catch {
        blockData = createEmptyData();
      }
    }
    __name(loadBlockData, "loadBlockData");
    async function saveBlockData() {
      const toSave = {
        version: blockData.version || 2,
        blockedUsers: blockData.blockedUsers || {},
        nicknameOnlyBlocks: blockData.nicknameOnlyBlocks || [],
        personaCache: {}
      };
      await safariSet({ [STORAGE_KEY]: JSON.stringify(toSave) });
    }
    __name(saveBlockData, "saveBlockData");
    function isBlocked2(personaId, nickname) {
      return isBlocked(blockData, personaId, nickname);
    }
    __name(isBlocked2, "isBlocked");
    async function blockUser(personaId, nickname) {
      if (personaId) {
        const existing = blockData.blockedUsers[personaId];
        blockData.blockedUsers[personaId] = {
          personaId,
          nickname,
          blockedAt: existing?.blockedAt ?? (/* @__PURE__ */ new Date()).toISOString()
        };
        blockData.nicknameOnlyBlocks = blockData.nicknameOnlyBlocks.filter(
          (b) => b.nickname !== nickname
        );
      } else {
        if (isBlocked2(void 0, nickname)) return;
        blockData.nicknameOnlyBlocks.push({
          nickname,
          blockedAt: (/* @__PURE__ */ new Date()).toISOString()
        });
      }
      await saveBlockData();
    }
    __name(blockUser, "blockUser");
    function qlFilterHintDialog() {
      return new Promise((resolve) => {
        const overlay = document.createElement("div");
        overlay.style.cssText = "position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:999999;display:flex;align-items:center;justify-content:center;";
        const dialog = document.createElement("div");
        dialog.style.cssText = "background:#1a1a1a;color:#e0e0e0;border-radius:14px;padding:20px;max-width:340px;width:90%;font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 24px rgba(0,0,0,0.4);";
        const title = document.createElement("p");
        title.textContent = "팁: 흐림 처리 모드";
        title.style.cssText = "font-size:16px;font-weight:600;margin:0 0 10px;";
        const msg = document.createElement("p");
        msg.textContent = "차단된 글을 완전히 숨기는 대신 흐리게만 처리할 수도 있어요. 익스텐션 팝업의 '흐림 처리' 토글에서 켤 수 있습니다.";
        msg.style.cssText = "font-size:14px;margin:0 0 18px;line-height:1.5;color:#bbb;";
        const btnRow = document.createElement("div");
        btnRow.style.cssText = "display:flex;gap:10px;";
        const dontBtn = document.createElement("button");
        dontBtn.textContent = "다시 보지 않기";
        dontBtn.style.cssText = "flex:1;padding:10px;border:1px solid #444;background:transparent;color:#aaa;border-radius:8px;font-size:13px;cursor:pointer;";
        const okBtn = document.createElement("button");
        okBtn.textContent = "확인";
        okBtn.style.cssText = "flex:1;padding:10px;border:none;background:#4A6CF7;color:#fff;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;";
        function close(result) {
          overlay.remove();
          resolve(result);
        }
        __name(close, "close");
        dontBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          close("dontShow");
        });
        okBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          close("confirm");
        });
        overlay.addEventListener("click", (e) => {
          if (e.target === overlay) close("confirm");
        });
        btnRow.appendChild(dontBtn);
        btnRow.appendChild(okBtn);
        dialog.appendChild(title);
        dialog.appendChild(msg);
        dialog.appendChild(btnRow);
        overlay.appendChild(dialog);
        document.body.appendChild(overlay);
      });
    }
    __name(qlFilterHintDialog, "qlFilterHintDialog");
    async function maybeShowFilterModeHint() {
      if (filterMode === "blur") return;
      if (dontShowFilterHint) return;
      const result = await qlFilterHintDialog();
      if (result === "dontShow") {
        dontShowFilterHint = true;
        try {
          await safariSet({ [DONT_SHOW_FILTER_HINT_KEY]: true });
        } catch {
        }
      }
    }
    __name(maybeShowFilterModeHint, "maybeShowFilterModeHint");
    const personaMap = /* @__PURE__ */ new Map();
    const personaCache = /* @__PURE__ */ new Map();
    function installApiInterceptor() {
      window.addEventListener("message", (event) => {
        if (event.data?.type !== "QUIET_LOUNGE_API_DATA") return;
        const mapData = event.data.personaMap;
        const cacheData = event.data.personaCache;
        if (mapData && typeof mapData === "object") {
          for (const [postId, personaId] of Object.entries(mapData)) {
            personaMap.set(postId, personaId);
          }
        }
        if (cacheData && typeof cacheData === "object") {
          for (const [personaId, nickname] of Object.entries(cacheData)) {
            personaCache.set(personaId, { nickname });
          }
        }
        filterAll();
        autoPromoteBlocks();
      });
      window.postMessage({ type: "QUIET_LOUNGE_REQUEST_DATA" }, "*");
    }
    __name(installApiInterceptor, "installApiInterceptor");
    async function autoPromoteBlocks() {
      let changed = false;
      for (const [pid, { nickname }] of personaCache) {
        const idx = blockData.nicknameOnlyBlocks.findIndex((b) => b.nickname === nickname);
        if (idx !== -1) {
          const block = blockData.nicknameOnlyBlocks.splice(idx, 1)[0];
          blockData.blockedUsers[pid] = {
            personaId: pid,
            nickname,
            blockedAt: block.blockedAt
          };
          changed = true;
        }
        if (blockData.blockedUsers[pid] && blockData.blockedUsers[pid].nickname !== nickname) {
          blockData.blockedUsers[pid].nickname = nickname;
          changed = true;
        }
      }
      if (changed) await saveBlockData();
    }
    __name(autoPromoteBlocks, "autoPromoteBlocks");
    function filterAll() {
      if (!isActivePage()) return;
      const totalBlocked = runFilterPass({
        blockData,
        filterMode,
        personaIdForPost: /* @__PURE__ */ __name((id) => personaMap.get(id), "personaIdForPost")
      });
      browser.runtime.sendMessage({ type: "UPDATE_BADGE", count: totalBlocked });
    }
    __name(filterAll, "filterAll");
    const QL_TAP_THROUGH_GUARD_MS = 350;
    function qlConfirm(message) {
      return new Promise((resolve) => {
        const overlay = document.createElement("div");
        overlay.style.cssText = "position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:999999;display:flex;align-items:center;justify-content:center;";
        const dialog = document.createElement("div");
        dialog.style.cssText = "background:#1a1a1a;color:#e0e0e0;border-radius:14px;padding:20px;max-width:300px;width:90%;text-align:center;font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 24px rgba(0,0,0,0.4);";
        const msg = document.createElement("p");
        msg.textContent = message;
        msg.style.cssText = "font-size:15px;margin:0 0 18px;line-height:1.4;";
        const btnRow = document.createElement("div");
        btnRow.style.cssText = "display:flex;gap:10px;";
        const cancelBtn = document.createElement("button");
        cancelBtn.textContent = "취소";
        cancelBtn.style.cssText = "flex:1;padding:10px;border:1px solid #444;background:transparent;color:#aaa;border-radius:8px;font-size:14px;cursor:pointer;";
        const confirmBtn = document.createElement("button");
        confirmBtn.textContent = "차단";
        confirmBtn.style.cssText = "flex:1;padding:10px;border:none;background:#e74c3c;color:#fff;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;";
        let armed = false;
        setTimeout(() => {
          armed = true;
        }, QL_TAP_THROUGH_GUARD_MS);
        function close(result) {
          overlay.remove();
          resolve(result);
        }
        __name(close, "close");
        cancelBtn.addEventListener("click", (e) => {
          if (!armed) return;
          e.stopPropagation();
          close(false);
        });
        confirmBtn.addEventListener("click", (e) => {
          if (!armed) return;
          e.stopPropagation();
          close(true);
        });
        overlay.addEventListener("click", (e) => {
          if (!armed) return;
          if (e.target === overlay) close(false);
        });
        btnRow.appendChild(cancelBtn);
        btnRow.appendChild(confirmBtn);
        dialog.appendChild(msg);
        dialog.appendChild(btnRow);
        overlay.appendChild(dialog);
        document.body.appendChild(overlay);
      });
    }
    __name(qlConfirm, "qlConfirm");
    const liveButtons = /* @__PURE__ */ new WeakSet();
    const injectButtonsAdapter = {
      buttonClassName: "quiet-lounge-btn",
      pathBMissingPidStrategy: "show-error",
      createButton() {
        const btn = document.createElement("button");
        btn.className = "quiet-lounge-btn";
        btn.textContent = "✕";
        btn.title = "이 유저 차단";
        btn.style.cssText = "margin-left:6px;cursor:pointer;opacity:0.6;font-size:12px;border:1px solid rgba(255,80,80,0.3);background:rgba(255,80,80,0.08);padding:1px 5px;line-height:1.2;color:#ff5050;border-radius:4px;vertical-align:middle;transition:all 0.15s;position:relative;z-index:10;";
        btn.addEventListener("mouseenter", () => {
          btn.style.opacity = "1";
          btn.style.background = "rgba(255,80,80,0.2)";
          btn.style.borderColor = "rgba(255,80,80,0.6)";
        });
        btn.addEventListener("mouseleave", () => {
          btn.style.opacity = "0.6";
          btn.style.background = "rgba(255,80,80,0.08)";
          btn.style.borderColor = "rgba(255,80,80,0.3)";
        });
        btn.addEventListener("mousedown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          e.stopImmediatePropagation();
        }, true);
        btn.addEventListener("pointerdown", (e) => {
          e.stopPropagation();
          e.stopImmediatePropagation();
        }, true);
        return btn;
      },
      shouldSkipExistingButton(existing) {
        return liveButtons.has(existing);
      },
      onButtonAttached(btn) {
        liveButtons.add(btn);
      },
      async onBlockClick(personaId, nickname) {
        if (!await qlConfirm(`"${nickname}" 유저를 차단하시겠습니까?`)) return;
        await blockUser(personaId, nickname);
        filterAll();
        runInjectBlockButtons();
        await maybeShowFilterModeHint();
      },
      async onMissingPersonaId() {
        await qlConfirm("personaId를 찾을 수 없습니다. 글 상세 페이지에서 차단해주세요.");
      }
    };
    function runInjectBlockButtons() {
      injectBlockButtons(injectButtonsAdapter, {
        findPersonaId: /* @__PURE__ */ __name((container) => findPersonaId(container, (id) => personaMap.get(id)), "findPersonaId"),
        nicknameForPersonaId: /* @__PURE__ */ __name((pid) => personaCache.get(pid)?.nickname, "nicknameForPersonaId")
      });
    }
    __name(runInjectBlockButtons, "runInjectBlockButtons");
    let lastPath = window.location.pathname;
    function watchNavigation() {
      window.addEventListener("popstate", onNavigate);
      window.addEventListener("pageshow", (e) => {
        if (e.persisted) {
          lastPath = "";
          onNavigate();
        }
      });
      const origPushState = history.pushState;
      history.pushState = function(...args) {
        origPushState.apply(this, args);
        onNavigate();
      };
      const origReplaceState = history.replaceState;
      history.replaceState = function(...args) {
        origReplaceState.apply(this, args);
        onNavigate();
      };
    }
    __name(watchNavigation, "watchNavigation");
    function onNavigate() {
      const newPath = window.location.pathname;
      if (newPath === lastPath) return;
      lastPath = newPath;
      profileStatsCache = { personaId: null, stats: null, monthlyPosts: null, monthlyComments: null };
      stopProfileStatsGuard();
      if (isActivePage()) {
        setTimeout(() => {
          filterAll();
          runInjectBlockButtons();
        }, 500);
      }
      if (isProfilePage()) {
        setTimeout(() => injectProfileStats(), 500);
      }
    }
    __name(onNavigate, "onNavigate");
    browser.storage.onChanged.addListener((changes) => {
      if (changes[STORAGE_KEY]) {
        try {
          blockData = JSON.parse(changes[STORAGE_KEY].newValue);
        } catch {
          blockData = createEmptyData();
        }
        filterAll();
      }
      if (changes[FILTER_MODE_KEY]) {
        filterMode = changes[FILTER_MODE_KEY].newValue || "hide";
        filterAll();
      }
      if (changes[DONT_SHOW_FILTER_HINT_KEY]) {
        dontShowFilterHint = !!changes[DONT_SHOW_FILTER_HINT_KEY].newValue;
      }
    });
    function isProfilePage() {
      return window.location.pathname.startsWith("/profiles/");
    }
    __name(isProfilePage, "isProfilePage");
    function getProfilePersonaId() {
      const match = window.location.pathname.match(/^\/profiles\/([^/?]+)/);
      return match ? match[1] : null;
    }
    __name(getProfilePersonaId, "getProfilePersonaId");
    async function fetchPersonaStats(personaId) {
      try {
        const resp = await fetch(`https://api.lounge.naver.com/user-api/v1/personas/${personaId}`, {
          credentials: "include"
        });
        if (!resp.ok) return null;
        const json = await resp.json();
        return json.data;
      } catch {
        return null;
      }
    }
    __name(fetchPersonaStats, "fetchPersonaStats");
    async function fetchMonthlyCount(personaId, type) {
      const now = /* @__PURE__ */ new Date();
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
      let count = 0;
      let cursor = "";
      const isComments = type === "comments";
      for (let page = 0; page < 50; page++) {
        try {
          const actUrl = `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/${type}?limit=100${cursor ? `&cursor=${cursor}` : ""}`;
          const actResp = await fetch(actUrl, { credentials: "include" });
          if (!actResp.ok) break;
          const actJson = await actResp.json();
          const items = actJson.data?.items || [];
          if (items.length === 0) break;
          let hasThisMonth = false;
          if (isComments) {
            const ids = items.map((item) => item.commentId);
            const params = ids.map((id) => `commentNoList=${id}`).join("&");
            const detailResp = await fetch(
              `https://api.lounge.naver.com/content-api/v1/comments?${params}`,
              { credentials: "include" }
            );
            if (!detailResp.ok) break;
            const detailJson = await detailResp.json();
            const raw = detailJson.data?.rawResponse;
            const parsed = raw ? JSON.parse(raw) : null;
            const commentList = parsed?.result?.commentList || [];
            for (const comment of commentList) {
              const dateStr = comment.regTimeGmt || "";
              if (dateStr && new Date(dateStr) >= monthStart) {
                count++;
                hasThisMonth = true;
              }
            }
          } else {
            const ids = items.map((item) => item.postId);
            const params = ids.map((id) => `postIds=${id}`).join("&");
            const detailResp = await fetch(
              `https://api.lounge.naver.com/content-api/v1/posts?${params}`,
              { credentials: "include" }
            );
            if (!detailResp.ok) break;
            const detailJson = await detailResp.json();
            const details = Array.isArray(detailJson.data) ? detailJson.data : [];
            for (const item of details) {
              const dateStr = item.createTime || "";
              if (dateStr && new Date(dateStr) >= monthStart) {
                count++;
                hasThisMonth = true;
              }
            }
          }
          if (!hasThisMonth) break;
          if (!actJson.data?.cursorInfo?.hasNext) break;
          cursor = actJson.data?.cursorInfo?.endCursor || "";
          if (!cursor) break;
        } catch {
          break;
        }
      }
      return count;
    }
    __name(fetchMonthlyCount, "fetchMonthlyCount");
    let profileStatsCache = {
      personaId: null,
      stats: null,
      monthlyPosts: null,
      monthlyComments: null
    };
    let profileStatsRafId = null;
    function buildProfileStatsHtml() {
      const stats = profileStatsCache.stats;
      const totalPosts = stats.totalPostCount || 0;
      const totalComments = stats.totalCommentCount || 0;
      const mp = profileStatsCache.monthlyPosts;
      const mc = profileStatsCache.monthlyComments;
      const spinner = `<span style="display:inline-block;width:14px;height:14px;border:2px solid rgba(255,255,255,0.2);border-top-color:${QL_PRIMARY};border-radius:50%;animation:ql-spin 0.8s linear infinite;vertical-align:middle;"></span>`;
      const monthlyPostsText = mp !== null ? mp : spinner;
      const monthlyCommentsText = mc !== null ? mc : spinner;
      return `<div style="font-weight:600;font-size:14px;margin-bottom:10px;color:${QL_PRIMARY};">활동 통계</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${totalPosts}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">총 작성글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${totalComments}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">총 댓글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${monthlyPostsText}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">이번달 작성글</div></div>
<div style="text-align:center;padding:8px;background:rgba(0,0,0,0.1);border-radius:8px;">
<div style="font-size:20px;font-weight:700;">${monthlyCommentsText}</div>
<div style="font-size:11px;opacity:0.7;margin-top:2px;">이번달 댓글</div></div></div>`;
    }
    __name(buildProfileStatsHtml, "buildProfileStatsHtml");
    if (!document.getElementById("ql-spinner-style")) {
      const style = document.createElement("style");
      style.id = "ql-spinner-style";
      style.textContent = "@keyframes ql-spin { to { transform: rotate(360deg); } }";
      document.head.appendChild(style);
    }
    function insertProfileStatsBox() {
      if (document.getElementById("ql-profile-stats")) return;
      const tabsEl = document.querySelector('[data-slot="tabs"]');
      if (!tabsEl) return;
      const box = document.createElement("div");
      box.id = "ql-profile-stats";
      box.style.cssText = "margin:12px 20px 0;padding:14px 16px;background:rgba(74,108,247,0.08);border:1px solid rgba(74,108,247,0.2);border-radius:10px;font-size:13px;color:var(--color-neutral-foreground-default,#e0e0e0);";
      box.innerHTML = buildProfileStatsHtml();
      tabsEl.before(box);
    }
    __name(insertProfileStatsBox, "insertProfileStatsBox");
    let profileStatsObserver = null;
    function startProfileStatsGuard() {
      stopProfileStatsGuard();
      const startTime = Date.now();
      function tick() {
        if (!isProfilePage() || !profileStatsCache.stats) {
          profileStatsRafId = null;
          return;
        }
        insertProfileStatsBox();
        if (Date.now() - startTime < 3e3) {
          profileStatsRafId = requestAnimationFrame(tick);
        } else {
          profileStatsRafId = null;
          profileStatsObserver = new MutationObserver(
            debounce(() => {
              if (isProfilePage() && profileStatsCache.stats) {
                insertProfileStatsBox();
              }
            }, 100)
          );
          profileStatsObserver.observe(document.body, { childList: true, subtree: true });
        }
      }
      __name(tick, "tick");
      profileStatsRafId = requestAnimationFrame(tick);
    }
    __name(startProfileStatsGuard, "startProfileStatsGuard");
    function stopProfileStatsGuard() {
      if (profileStatsRafId) {
        cancelAnimationFrame(profileStatsRafId);
        profileStatsRafId = null;
      }
      if (profileStatsObserver) {
        profileStatsObserver.disconnect();
        profileStatsObserver = null;
      }
    }
    __name(stopProfileStatsGuard, "stopProfileStatsGuard");
    function injectProfileStats() {
      if (!isProfilePage()) return;
      const personaId = getProfilePersonaId();
      if (!personaId) return;
      if (profileStatsCache.personaId === personaId && profileStatsCache.stats) {
        startProfileStatsGuard();
        return;
      }
      fetchPersonaStats(personaId).then((stats) => {
        if (!stats) return;
        if (stats.isOwner) {
          safariSet({ quiet_lounge_my_persona_id: personaId });
        }
        profileStatsCache = { personaId, stats, monthlyPosts: null, monthlyComments: null };
        const now = /* @__PURE__ */ new Date();
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
        const createTime = stats.createTime ? new Date(stats.createTime) : null;
        const createdThisMonth = createTime && createTime >= monthStart;
        if (createdThisMonth) {
          profileStatsCache.monthlyPosts = stats.totalPostCount || 0;
          profileStatsCache.monthlyComments = stats.totalCommentCount || 0;
        } else {
          fetchMonthlyCount(personaId, "posts").then((count) => {
            profileStatsCache.monthlyPosts = count;
            const el = document.getElementById("ql-profile-stats");
            if (el) el.innerHTML = buildProfileStatsHtml();
          });
          fetchMonthlyCount(personaId, "comments").then((count) => {
            profileStatsCache.monthlyComments = count;
            const el = document.getElementById("ql-profile-stats");
            if (el) el.innerHTML = buildProfileStatsHtml();
          });
        }
        startProfileStatsGuard();
      });
    }
    __name(injectProfileStats, "injectProfileStats");
    function saveMyStats(statsObj) {
      safariSet({
        quiet_lounge_my_stats: JSON.stringify(statsObj)
      });
    }
    __name(saveMyStats, "saveMyStats");
    async function fetchAndStoreMyStats() {
      try {
        const meResp = await fetch("https://api.lounge.naver.com/user-api/v1/members/me/personas", {
          credentials: "include"
        });
        if (!meResp.ok) {
          QLStorage.remove("quiet_lounge_my_stats");
          return;
        }
        const meJson = await meResp.json();
        const meData = Array.isArray(meJson.data) ? meJson.data[0] : meJson.data;
        if (!meData?.personaId) return;
        const personaId = meData.personaId;
        safariSet({ quiet_lounge_my_persona_id: personaId });
        let totalPosts = 0;
        let totalComments = 0;
        let nickname = meData.nickname || "";
        let createTime = meData.createTime ? new Date(meData.createTime) : null;
        try {
          const statsResp = await fetch(
            `https://api.lounge.naver.com/user-api/v1/personas/${personaId}`,
            { credentials: "include" }
          );
          if (statsResp.ok) {
            const statsJson = await statsResp.json();
            const sData = statsJson.data;
            if (sData) {
              totalPosts = sData.totalPostCount || 0;
              totalComments = sData.totalCommentCount || 0;
              nickname = sData.nickname || nickname;
              createTime = sData.createTime ? new Date(sData.createTime) : createTime;
            }
          }
        } catch {
          try {
            const postsResp = await fetch(
              `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/posts?limit=1`,
              { credentials: "include" }
            );
            if (postsResp.ok) {
              const pJson = await postsResp.json();
              totalPosts = pJson.data?.totalPostCount || 0;
            }
            const commentsResp = await fetch(
              `https://api.lounge.naver.com/user-api/v1/personas/${personaId}/activities/comments?limit=1`,
              { credentials: "include" }
            );
            if (commentsResp.ok) {
              const cJson = await commentsResp.json();
              totalComments = cJson.data?.totalCommentCount || cJson.data?.totalCount || 0;
            }
          } catch {
          }
        }
        const now = /* @__PURE__ */ new Date();
        const stats = {
          personaId,
          nickname,
          totalPosts,
          totalComments,
          monthlyPosts: "...",
          monthlyComments: "...",
          updatedAt: now.toISOString()
        };
        saveMyStats(stats);
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
        const createdThisMonth = createTime && createTime >= monthStart;
        if (createdThisMonth) {
          stats.monthlyPosts = totalPosts;
          stats.monthlyComments = totalComments;
          saveMyStats(stats);
        } else {
          fetchMonthlyCount(personaId, "posts").then((count) => {
            stats.monthlyPosts = count;
          }).catch(() => {
            stats.monthlyPosts = "?";
          }).finally(() => saveMyStats(stats));
          fetchMonthlyCount(personaId, "comments").then((count) => {
            stats.monthlyComments = count;
          }).catch(() => {
            stats.monthlyComments = "?";
          }).finally(() => saveMyStats(stats));
        }
      } catch {
      }
    }
    __name(fetchAndStoreMyStats, "fetchAndStoreMyStats");
    const QL_UA = typeof navigator !== "undefined" && navigator.userAgent || "";
    const QL_MAX_TOUCH = typeof navigator !== "undefined" && navigator.maxTouchPoints || 0;
    const QL_IS_IOS = /iPhone|iPad|iPod/.test(QL_UA) || /Mac/.test(QL_UA) && QL_MAX_TOUCH > 1;
    const QL_IS_MAC = /Macintosh/.test(QL_UA) && !QL_IS_IOS;
    const NOTIF_BANNER_DISMISSED_KEY = "quiet_lounge_notif_banner_dismissed";
    const KEYWORD_ALERTS_KEY_CS = "quiet_lounge_keyword_alerts";
    function showNotificationFromContent(payload) {
      if (typeof Notification === "undefined") return false;
      if (Notification.permission !== "granted") {
        maybeShowPermissionBanner(true);
        return false;
      }
      try {
        const tag = `ql_kw_${payload.postId}_${Date.now()}`;
        const url = `https://lounge.naver.com/posts/${payload.postId}`;
        const title = payload.titleB64 ? base64ToUtf8(payload.titleB64) : payload.title || "";
        const body = payload.bodyB64 ? base64ToUtf8(payload.bodyB64) : payload.body || "";
        const n = new Notification(title, {
          body,
          icon: payload.icon,
          tag,
          requireInteraction: true
        });
        n.onclick = () => {
          try {
            window.focus();
            window.open(url, "_blank");
          } catch {
          }
          n.close();
        };
        return true;
      } catch (e) {
        console.warn("[QL][cs] notification create failed", e);
        return false;
      }
    }
    __name(showNotificationFromContent, "showNotificationFromContent");
    function base64ToUtf8(b64) {
      try {
        const bin = atob(b64);
        const bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        return new TextDecoder().decode(bytes);
      } catch {
        return "";
      }
    }
    __name(base64ToUtf8, "base64ToUtf8");
    async function maybeShowPermissionBanner(force) {
      if (!QL_IS_MAC) return;
      if (typeof Notification === "undefined") return;
      if (Notification.permission === "granted") return;
      if (!force) {
        try {
          const result = await QLStorage.get([KEYWORD_ALERTS_KEY_CS, NOTIF_BANNER_DISMISSED_KEY]);
          if (result[NOTIF_BANNER_DISMISSED_KEY]) return;
          const alerts = result[KEYWORD_ALERTS_KEY_CS] ? JSON.parse(result[KEYWORD_ALERTS_KEY_CS]) : [];
          if (!alerts.some((a) => a.enabled)) return;
        } catch {
          return;
        }
      }
      const existing = document.getElementById("ql-notif-banner");
      if (existing) existing.remove();
      const isDenied = Notification.permission === "denied";
      const banner = document.createElement("div");
      banner.id = "ql-notif-banner";
      banner.style.cssText = [
        "position:fixed",
        "top:16px",
        "right:16px",
        "z-index:2147483647",
        `background:${QL_PRIMARY}`,
        "color:#fff",
        "padding:12px 16px",
        "border-radius:8px",
        "box-shadow:0 4px 12px rgba(0,0,0,0.3)",
        "font-family:-apple-system,BlinkMacSystemFont,sans-serif",
        "font-size:13px",
        "max-width:340px",
        "display:flex",
        "gap:12px",
        "align-items:center"
      ].join(";");
      const message = isDenied ? "QuietLounge 키워드 알림 권한이 거부되었습니다. 사파리 설정 → 웹사이트 → 알림에서 lounge.naver.com을 허용으로 바꾸세요." : "QuietLounge 키워드 알림을 받으려면 알림 권한을 허용해 주세요.";
      const allowLabel = "허용";
      const closeLabel = "닫기";
      const msgSpan = document.createElement("span");
      msgSpan.style.cssText = "flex:1";
      msgSpan.textContent = message;
      const allowBtn = document.createElement("button");
      allowBtn.id = "ql-notif-allow";
      allowBtn.style.cssText = `background:#fff;color:${QL_PRIMARY};border:none;padding:6px 12px;border-radius:4px;font-weight:600;cursor:pointer`;
      allowBtn.textContent = allowLabel;
      if (isDenied) allowBtn.style.display = "none";
      const closeBtn = document.createElement("button");
      closeBtn.id = "ql-notif-dismiss";
      closeBtn.style.cssText = "background:transparent;color:#fff;border:1px solid rgba(255,255,255,0.5);padding:6px 10px;border-radius:4px;cursor:pointer";
      closeBtn.textContent = closeLabel;
      banner.appendChild(msgSpan);
      banner.appendChild(allowBtn);
      banner.appendChild(closeBtn);
      document.body.appendChild(banner);
      allowBtn.addEventListener("click", () => {
        try {
          const ret = Notification.requestPermission((perm) => {
            handlePermResult(perm);
          });
          if (ret && typeof ret.then === "function") {
            ret.then(handlePermResult).catch(() => {
            });
          }
        } catch {
        }
      });
      closeBtn.addEventListener("click", () => {
        banner.remove();
        QLStorage.set({ [NOTIF_BANNER_DISMISSED_KEY]: true });
      });
      function handlePermResult(perm) {
        if (perm === "granted") {
          try {
            new Notification("QuietLounge", {
              body: "키워드 알림이 활성화되었습니다."
            });
          } catch {
          }
        }
        banner.remove();
        QLStorage.set({ [NOTIF_BANNER_DISMISSED_KEY]: true });
      }
      __name(handlePermResult, "handlePermResult");
    }
    __name(maybeShowPermissionBanner, "maybeShowPermissionBanner");
    browser.runtime.onMessage.addListener((message, _sender, sendResponse) => {
      if (message.type === "REFRESH_MY_STATS") {
        fetchAndStoreMyStats();
        return;
      }
      if (message.type === "QL_SHOW_NOTIFICATION") {
        const ok = showNotificationFromContent(message.payload || {});
        sendResponse({ ok });
        return true;
      }
      if (message.type === "QL_PROMPT_NOTIF_PERM") {
        QLStorage.remove(NOTIF_BANNER_DISMISSED_KEY).then(() => {
          maybeShowPermissionBanner(true);
        });
        sendResponse({
          ok: true,
          permission: typeof Notification !== "undefined" ? Notification.permission : "unsupported"
        });
        return true;
      }
    });
    let lastBlockDataHash = JSON.stringify(blockData);
    let pollTimer = null;
    function startBlockDataPolling() {
      if (pollTimer) return;
      pollTimer = setInterval(async () => {
        try {
          const result = await QLStorage.get([
            STORAGE_KEY,
            FILTER_MODE_KEY,
            "quiet_lounge_refresh_stats"
          ]);
          const raw = result[STORAGE_KEY] || "";
          if (raw && raw !== lastBlockDataHash) {
            lastBlockDataHash = raw;
            blockData = JSON.parse(raw);
            if (isActivePage()) filterAll();
          }
          const newMode = result[FILTER_MODE_KEY];
          if (newMode && newMode !== filterMode) {
            filterMode = newMode;
            if (isActivePage()) filterAll();
          }
          if (result.quiet_lounge_refresh_stats) {
            await QLStorage.remove("quiet_lounge_refresh_stats");
            fetchAndStoreMyStats();
          }
        } catch {
        }
      }, 3e3);
    }
    __name(startBlockDataPolling, "startBlockDataPolling");
    function stopBlockDataPolling() {
      if (pollTimer) {
        clearInterval(pollTimer);
        pollTimer = null;
      }
    }
    __name(stopBlockDataPolling, "stopBlockDataPolling");
    document.addEventListener("visibilitychange", () => {
      if (document.visibilityState === "visible") startBlockDataPolling();
      else stopBlockDataPolling();
    });
    if (document.visibilityState === "visible") startBlockDataPolling();
    async function init() {
      await loadBlockData();
      fetchAndStoreMyStats();
      installApiInterceptor();
      watchNavigation();
      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", start);
      } else {
        start();
      }
    }
    __name(init, "init");
    function start() {
      if (isActivePage()) {
        filterAll();
        runInjectBlockButtons();
      }
      injectProfileStats();
      maybeShowPermissionBanner();
      const target = document.querySelector(SEL.scrollContainer) || document.body;
      const debouncedUpdate = debounce(() => {
        if (isActivePage()) {
          filterAll();
          runInjectBlockButtons();
        }
        injectProfileStats();
      }, 200);
      const observer = new MutationObserver(debouncedUpdate);
      observer.observe(target, { childList: true, subtree: true });
    }
    __name(start, "start");
    init();
  })();
})();
