// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.
// Source: shared/web/. Edit there and run `pnpm build`.

"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

  // shared/web/entries/safari-storage-bridge.ts
  (function() {
    "use strict";
    const browser = globalThis.browser || globalThis.chrome;
    if (!browser?.runtime?.sendMessage) {
      return;
    }
    const ua = typeof navigator !== "undefined" && navigator.userAgent || "";
    const maxTouch = typeof navigator !== "undefined" && navigator.maxTouchPoints || 0;
    const isAppleMobile = /iPhone|iPad|iPod/.test(ua) || /Mac/.test(ua) && maxTouch > 1;
    const isMacOS = /Macintosh/.test(ua) && !isAppleMobile;
    if (isMacOS) {
      return;
    }
    const originalGet = browser.storage?.local?.get?.bind(browser.storage.local);
    const originalRemove = browser.storage?.local?.remove?.bind(browser.storage.local);
    function sendBg(payload) {
      return new Promise((resolve, reject) => {
        let settled = false;
        const handle = /* @__PURE__ */ __name((response) => {
          if (settled) return;
          settled = true;
          if (!response || response.ok === false) {
            reject(new Error(response?.error || "no response"));
            return;
          }
          resolve(response.response || {});
        }, "handle");
        const fail = /* @__PURE__ */ __name((err) => {
          if (settled) return;
          settled = true;
          reject(err);
        }, "fail");
        try {
          const maybe = browser.runtime.sendMessage(payload, (response) => {
            const err = browser.runtime.lastError;
            if (err) {
              fail(err);
              return;
            }
            handle(response);
          });
          if (maybe && typeof maybe.then === "function") {
            maybe.then(handle, fail);
          }
        } catch (e) {
          fail(e);
        }
      });
    }
    __name(sendBg, "sendBg");
    function normalizeKeys(keys) {
      if (keys === null || keys === void 0) return [];
      if (typeof keys === "string") return [keys];
      if (Array.isArray(keys)) return keys.slice();
      if (typeof keys === "object") return Object.keys(keys);
      return [];
    }
    __name(normalizeKeys, "normalizeKeys");
    function applyDefaults(keys, result) {
      if (keys && typeof keys === "object" && !Array.isArray(keys)) {
        for (const k of Object.keys(keys)) {
          if (!(k in result)) result[k] = keys[k];
        }
      }
      return result;
    }
    __name(applyDefaults, "applyDefaults");
    const changeListeners = /* @__PURE__ */ new Set();
    const lastSnapshot = {};
    function notifyChange(changes) {
      for (const fn of changeListeners) {
        try {
          fn(changes, "local");
        } catch {
        }
      }
    }
    __name(notifyChange, "notifyChange");
    async function bridgedGet(keys) {
      const normalized = normalizeKeys(keys);
      if (normalized.length === 0) return {};
      try {
        const response = await sendBg({ type: "QL_STORAGE_GET", keys: normalized });
        const data = response?.data || {};
        for (const k of normalized) {
          if (k in data) lastSnapshot[k] = data[k];
        }
        return applyDefaults(keys, { ...data });
      } catch {
        return applyDefaults(keys, {});
      }
    }
    __name(bridgedGet, "bridgedGet");
    async function bridgedSet(items) {
      if (!items || typeof items !== "object") return;
      try {
        await sendBg({ type: "QL_STORAGE_SET", items });
      } catch {
        return;
      }
      const changes = {};
      for (const [k, v] of Object.entries(items)) {
        changes[k] = { newValue: v, oldValue: lastSnapshot[k] };
        lastSnapshot[k] = v;
      }
      notifyChange(changes);
    }
    __name(bridgedSet, "bridgedSet");
    async function bridgedRemove(keys) {
      const normalized = normalizeKeys(keys);
      if (normalized.length === 0) return;
      try {
        await sendBg({ type: "QL_STORAGE_REMOVE", keys: normalized });
      } catch {
        return;
      }
      const changes = {};
      for (const k of normalized) {
        changes[k] = { oldValue: lastSnapshot[k] };
        delete lastSnapshot[k];
      }
      notifyChange(changes);
    }
    __name(bridgedRemove, "bridgedRemove");
    const helper = {
      get: bridgedGet,
      set: bridgedSet,
      remove: bridgedRemove,
      onChanged: {
        addListener: /* @__PURE__ */ __name((fn) => {
          changeListeners.add(fn);
        }, "addListener"),
        removeListener: /* @__PURE__ */ __name((fn) => {
          changeListeners.delete(fn);
        }, "removeListener"),
        hasListener: /* @__PURE__ */ __name((fn) => changeListeners.has(fn), "hasListener")
      },
      _ready: true
    };
    try {
      Object.defineProperty(globalThis, "__QL_storage", {
        value: helper,
        writable: false,
        configurable: false,
        enumerable: false
      });
    } catch {
      globalThis.__QL_storage = helper;
    }
    try {
      if (browser.storage && browser.storage.local) {
        try {
          browser.storage.local.get = bridgedGet;
          browser.storage.local.set = bridgedSet;
          browser.storage.local.remove = bridgedRemove;
          browser.storage.local.clear = async () => {
          };
        } catch {
        }
        try {
          browser.storage.onChanged = helper.onChanged;
        } catch {
        }
      }
    } catch {
    }
    (/* @__PURE__ */ __name((async function migrateLegacy() {
      const MIGRATION_KEY = "__ql_legacy_storage_migrated_v1";
      const LEGACY_KEYS = [
        "quiet_lounge_data",
        "quiet_lounge_filter_mode",
        "quiet_lounge_my_stats",
        "quiet_lounge_my_persona_id"
      ];
      try {
        const flag = await sendBg({ type: "QL_STORAGE_GET", keys: [MIGRATION_KEY] });
        if (flag?.data?.[MIGRATION_KEY]) return;
        if (!originalGet) {
          await sendBg({ type: "QL_STORAGE_SET", items: { [MIGRATION_KEY]: true } });
          return;
        }
        const legacy = await originalGet(LEGACY_KEYS);
        const items = {};
        for (const key of LEGACY_KEYS) {
          if (legacy && legacy[key] !== void 0) items[key] = legacy[key];
        }
        if (Object.keys(items).length > 0) {
          const existing = await sendBg({ type: "QL_STORAGE_GET", keys: Object.keys(items) });
          const toWrite = {};
          for (const [k, v] of Object.entries(items)) {
            if (!(k in (existing?.data || {}))) toWrite[k] = v;
          }
          if (Object.keys(toWrite).length > 0) {
            await sendBg({ type: "QL_STORAGE_SET", items: toWrite });
          }
          if (originalRemove) {
            try {
              await originalRemove(LEGACY_KEYS);
            } catch {
            }
          }
        }
        await sendBg({ type: "QL_STORAGE_SET", items: { [MIGRATION_KEY]: true } });
      } catch {
      }
    }), "migrateLegacy"))();
  })();
})();
