import XCTest
@testable import QuietLoungeCore

/// `WebViewScripts.afterScript` / `renderTemplate` 의 placeholder 치환 + 빌드 산출물 정합성 검증.
///
/// 이전엔 placeholder 치환이 따옴표 매칭 실수로 영원히 실패해도 (Bug #1) 런타임에서 silent
/// 회귀 — 테스트 가드 없음. 또 빌드 산출물 (`Resources/webview-scripts/after.js`) 누락 시
/// `assertionFailure` 가 release 에서 no-op 라 빈 WKUserScript 가 그대로 등록되어 차단/블러가
/// 통째로 죽어도 크래시 없이 silent (P2 리뷰 피드백).
///
/// 이 테스트는:
/// 1. **순수 시맨틱**: synthetic template 으로 `renderTemplate` 의 bare-token 치환 동작 검증
/// 2. **산출물 정합성**: `pnpm build` 가 만든 실제 after.js 를 file system 으로 직접 읽어
///    `renderTemplate` 통과 후 `window.__QL_BLOCK_DATA = {…}` / `window.__QL_FILTER_MODE = "blur"`
///    같은 정상 코드가 나오는지, placeholder 흔적이 없는지 검증
final class WebViewScriptsTests: XCTestCase {

    // MARK: - 순수 시맨틱 (synthetic template)

    func test_renderTemplate_blockData_치환() {
        let template = """
        window.__QL_BLOCK_DATA = __QL_BLOCK_DATA_PLACEHOLDER__;
        """
        let result = WebViewScripts.renderTemplate(
            template,
            blockData: ["version": 2, "blockedUsers": [String: Any]()],
            filterMode: "hide"
        )
        // bare token 이 JSON 으로 치환되어야 한다 (따옴표 없이 객체 리터럴).
        XCTAssertTrue(result.contains("window.__QL_BLOCK_DATA = {"))
        XCTAssertFalse(result.contains("__QL_BLOCK_DATA_PLACEHOLDER__"))
    }

    func test_renderTemplate_filterMode_치환_double_quote() {
        // esbuild 산출물은 string literal 을 double quote 로 출력. 따옴표는 보존되고 식별자만 치환.
        let template = #"window.__QL_FILTER_MODE = "__QL_FILTER_MODE_PLACEHOLDER__";"#
        let result = WebViewScripts.renderTemplate(template, blockData: [:], filterMode: "blur")
        XCTAssertTrue(result.contains(#"window.__QL_FILTER_MODE = "blur";"#))
        XCTAssertFalse(result.contains("__QL_FILTER_MODE_PLACEHOLDER__"))
    }

    func test_renderTemplate_filterMode_치환_single_quote() {
        // 만약 산출물이 single quote 로 출력돼도 (esbuild 옵션 변경 / 다른 번들러 도입 시) 동작해야 함.
        let template = "window.__QL_FILTER_MODE = '__QL_FILTER_MODE_PLACEHOLDER__';"
        let result = WebViewScripts.renderTemplate(template, blockData: [:], filterMode: "hide")
        XCTAssertTrue(result.contains("window.__QL_FILTER_MODE = 'hide';"))
    }

    func test_renderTemplate_blockData_직렬화_실패시_빈_객체() {
        // JSONSerialization.data 가 실패할 수 있는 입력 (NSString/NSNumber/NSArray/NSDictionary/NSNull외 타입) 시 빈 객체로 fallback. Date 는 JSON 호환 타입이 아니라 실제로 실패 경로를 탄다.
        let template = "var x = __QL_BLOCK_DATA_PLACEHOLDER__;"
        let invalid: [String: Any] = ["bad": Date()]
        let result = WebViewScripts.renderTemplate(template, blockData: invalid, filterMode: "hide")
        XCTAssertTrue(result.contains("var x = {};"))
    }

    // MARK: - 빌드 산출물 정합성

    /// 프로젝트 root 에서 실제 빌드 산출물의 절대 경로 계산.
    /// CI 가 `pnpm build` 후 `swift test` 를 돌리므로 산출물이 존재해야 함.
    private func locateAfterJsArtifact() -> URL {
        // #filePath: 이 파일의 절대 경로 (.../swift-tests/Tests/QuietLoungeCoreTests/WebViewScriptsTests.swift)
        let testFile = URL(fileURLWithPath: #filePath)
        let projectRoot = testFile
            .deletingLastPathComponent() // QuietLoungeCoreTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // swift-tests
            .deletingLastPathComponent() // <project root>
        return projectRoot
            .appendingPathComponent("safari-extension")
            .appendingPathComponent("QuietLounge")
            .appendingPathComponent("iOS (App)")
            .appendingPathComponent("Resources")
            .appendingPathComponent("webview-scripts")
            .appendingPathComponent("after.js")
    }

    func test_artifact_existence_with_auto_generated_header() throws {
        let url = locateAfterJsArtifact()
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: url.path),
            "after.js 산출물이 존재하지 않음 — `pnpm build` 가 먼저 실행되어야 함. 경로: \(url.path)"
        )
        let content = try String(contentsOf: url, encoding: .utf8)
        XCTAssertTrue(
            content.contains("auto-generated by scripts/build.mjs"),
            "산출물에 auto-generated 헤더가 없음 — 누군가 산출물을 직접 수정했거나 잘못된 파일."
        )
        // bare placeholder 토큰이 산출물에 살아 있어야 (Swift 측 치환 대상).
        XCTAssertTrue(content.contains("__QL_BLOCK_DATA_PLACEHOLDER__"))
        XCTAssertTrue(content.contains("__QL_FILTER_MODE_PLACEHOLDER__"))
    }

    func test_artifact_renderTemplate_e2e() throws {
        // 실제 산출물 + 실제 blockData 형태로 e2e 치환 동작 검증.
        // afterScript 함수 자체는 Bundle.main 에 의존하지만, renderTemplate 으로 같은 substitution
        // 로직을 테스트할 수 있다 — Bundle 누락 시 release 에서도 fail-fast 하도록 preconditionFailure
        // 처리는 별도 가드.
        let url = locateAfterJsArtifact()
        let template = try String(contentsOf: url, encoding: .utf8)
        let blockData: [String: Any] = [
            "version": 2,
            "blockedUsers": ["pid1": ["personaId": "pid1", "nickname": "테스트", "blockedAt": ""]],
            "nicknameOnlyBlocks": [[String: Any]](),
        ]
        let result = WebViewScripts.renderTemplate(template, blockData: blockData, filterMode: "blur")

        // 1. placeholder 흔적 0
        XCTAssertFalse(result.contains("__QL_BLOCK_DATA_PLACEHOLDER__"))
        XCTAssertFalse(result.contains("__QL_FILTER_MODE_PLACEHOLDER__"))

        // 2. window.__QL_BLOCK_DATA 가 정상 객체 리터럴로 들어감
        XCTAssertTrue(result.contains("window.__QL_BLOCK_DATA = {"))
        XCTAssertTrue(result.contains("\"pid1\""))

        // 3. window.__QL_FILTER_MODE 가 "blur" 로 (따옴표 종류 무관)
        XCTAssertTrue(
            result.contains(#"window.__QL_FILTER_MODE = "blur""#) ||
            result.contains("window.__QL_FILTER_MODE = 'blur'"),
            "filterMode 가 산출물에 정상 치환되지 않음"
        )

        // 4. esbuild 가 keepNames 옵션으로 보존하는 핵심 함수명이 살아있음 (회귀 가드).
        XCTAssertTrue(result.contains("function isCleanbotFiltered"))
    }

    func test_placeholder_constants_match_source_artifact() {
        // Swift 측 placeholder 상수가 entry source / esbuild 산출물의 토큰과 정확히 일치해야 함.
        // web/entries/ios-after.ts 와 placeholders.d.ts 의 토큰명이 바뀌면 이 테스트가 깨지고
        // 즉시 재동기화 필요함을 알림.
        XCTAssertEqual(WebViewScripts.blockDataPlaceholder, "__QL_BLOCK_DATA_PLACEHOLDER__")
        XCTAssertEqual(WebViewScripts.filterModePlaceholder, "__QL_FILTER_MODE_PLACEHOLDER__")
    }
}
