#!/usr/bin/env node
// QuietLounge — 4 개 플랫폼 (Chrome / Safari ext / iOS native WebView / Android WebView) 의
// 라운지 페이지 inject 스크립트를 단일 source (shared/web/) 에서 esbuild 로 동시 빌드.
//
// 산출물은 각 플랫폼이 이미 읽고 있는 in-place 위치에 떨어지므로 manifest / 코드 변경이 0:
//
//   chrome-extension/content-scripts/main.js
//   safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/main.js
//   safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/after.js
//   android-app/app/src/main/assets/webview-scripts/after.js
//
// iOS / Android entry 는 native bridge 가 빌드 후 텍스트 치환으로 주입할 placeholder
// (`__QL_BLOCK_DATA_PLACEHOLDER__`, `'__QL_FILTER_MODE_PLACEHOLDER__'`) 가 그대로
// 살아남아야 한다 — minify=false + treeShaking=false 로 보존. tests/build/artifacts.test.js
// 가 회귀 가드.
//
// CLI:
//   node scripts/build.mjs           # 1 회 빌드
//   node scripts/build.mjs --watch   # watch 모드 (개발용)
//   node scripts/build.mjs --check   # 빌드 + git diff --exit-code 로 산출물 drift 검출

import { context, build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const BANNER = [
  '// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.',
  '// Source: shared/web/. Edit there and run `pnpm build`.',
  '',
].join('\n');

const TARGETS = [
  {
    name: 'chrome',
    entryPoints: [path.join(ROOT, 'shared/web/entries/chrome.ts')],
    outfile: path.join(ROOT, 'chrome-extension/content-scripts/main.js'),
  },
  {
    name: 'safari-ext',
    entryPoints: [path.join(ROOT, 'shared/web/entries/safari-ext.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/main.js',
    ),
  },
  {
    name: 'chrome-api-interceptor',
    entryPoints: [path.join(ROOT, 'shared/web/entries/web-api-interceptor.ts')],
    outfile: path.join(ROOT, 'chrome-extension/content-scripts/api-interceptor.js'),
  },
  {
    name: 'safari-api-interceptor',
    entryPoints: [path.join(ROOT, 'shared/web/entries/web-api-interceptor.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/api-interceptor.js',
    ),
  },
  {
    name: 'safari-injector',
    entryPoints: [path.join(ROOT, 'shared/web/entries/safari-injector.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/injector.js',
    ),
  },
  {
    name: 'safari-storage-bridge',
    entryPoints: [path.join(ROOT, 'shared/web/entries/safari-storage-bridge.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/storage-bridge.js',
    ),
  },
  {
    name: 'ios-after',
    entryPoints: [path.join(ROOT, 'shared/web/entries/ios-after.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/after.js',
    ),
  },
  {
    name: 'ios-before',
    entryPoints: [path.join(ROOT, 'shared/web/entries/ios-before.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/before.js',
    ),
  },
  {
    name: 'android-after',
    entryPoints: [path.join(ROOT, 'shared/web/entries/android-after.ts')],
    outfile: path.join(ROOT, 'android-app/app/src/main/assets/webview-scripts/after.js'),
  },
  {
    name: 'android-before',
    entryPoints: [path.join(ROOT, 'shared/web/entries/android-before.ts')],
    outfile: path.join(ROOT, 'android-app/app/src/main/assets/webview-scripts/before.js'),
  },
];

/** 산출물 drift 검출용 — `--check` 시 빌드 후 git diff --exit-code 로 검사할 path 들. */
const ARTIFACT_PATHS = TARGETS.map((t) => path.relative(ROOT, t.outfile));

const COMMON = {
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  // 한국어 / 이모지 등 비-ASCII 문자열을 그대로 보존 — 기본은 \uXXXX escape 라
  // 산출물 grep ("클린봇", "감지") 가드와 시각적 가독성이 모두 깨진다.
  charset: 'utf8',
  // placeholder + 함수명 보존 — native bridge 와 source-level guard 테스트가 의존.
  minify: false,
  treeShaking: false,
  keepNames: true,
  legalComments: 'none',
  banner: { js: BANNER },
  loader: { '.ts': 'ts' },
  logLevel: 'info',
};

const args = new Set(process.argv.slice(2));
const watch = args.has('--watch');
const check = args.has('--check');

async function buildAll() {
  await Promise.all(
    TARGETS.map(async (t) => {
      const opts = { ...COMMON, entryPoints: t.entryPoints, outfile: t.outfile };
      await build(opts);
      console.log(`✓ ${t.name.padEnd(14)} → ${path.relative(ROOT, t.outfile)}`);
    }),
  );
}

async function watchAll() {
  await Promise.all(
    TARGETS.map(async (t) => {
      const opts = { ...COMMON, entryPoints: t.entryPoints, outfile: t.outfile };
      const ctx = await context(opts);
      await ctx.watch();
      console.log(`👀 watching ${t.name.padEnd(11)} → ${path.relative(ROOT, t.outfile)}`);
    }),
  );
}

function checkDrift() {
  // git 가 없는 환경(tarball 등) 에서는 skip.
  try {
    execFileSync('git', ['rev-parse', '--git-dir'], { cwd: ROOT, stdio: 'ignore' });
  } catch {
    console.log('• git 없음 — drift 검사 skip');
    return;
  }
  try {
    execFileSync('git', ['diff', '--exit-code', '--', ...ARTIFACT_PATHS], {
      cwd: ROOT,
      stdio: 'inherit',
    });
    console.log('✓ 빌드 산출물 = git (drift 없음)');
  } catch {
    console.error('✗ 빌드 산출물이 git 와 다름 — `pnpm build` 후 변경분을 commit 하세요.');
    process.exit(1);
  }
}

if (watch) {
  await watchAll();
  // watch 는 자체 종료 안 함 — Ctrl+C 까지 idle.
} else {
  await buildAll();
  if (check) checkDrift();
}
