#!/usr/bin/env node
// QuietLounge — 4 개 플랫폼 (Chrome / Safari ext / iOS native WebView / Android WebView) 의
// 라운지 페이지 inject 스크립트를 단일 source (web/) 에서 esbuild 로 동시 빌드.
//
// 산출물은 각 플랫폼이 이미 읽고 있는 in-place 위치에 떨어지므로 manifest / 코드 변경이 0:
//
//   chrome-extension/content-scripts/main.js
//   safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/main.js
//   safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/after.js
//   android-app/app/src/main/assets/webview-scripts/after.js
//
// iOS / Android entry 는 native bridge 가 빌드 후 텍스트 치환으로 주입할 placeholder
// (`__QL_BLOCK_DATA_PLACEHOLDER__`, `'__QL_FILTER_MODE_PLACEHOLDER__'`) 가 그대로
// 살아남아야 한다 — minify=false + treeShaking=false 로 보존. tests/build/artifacts.test.js
// 가 회귀 가드.
//
// CLI:
//   node scripts/build.mjs           # 1 회 빌드
//   node scripts/build.mjs --watch   # watch 모드 (개발용)
//   node scripts/build.mjs --check   # 빌드 + git diff --exit-code (legacy)
//
// 산출물은 .gitignore 라 `--check` 의 git diff 가 ignored 파일을 검증하지 못함 — 이 flag 는
// 산출물이 다시 git 에 들어오는 케이스를 위한 백호환 잔재이고, 현재 정책 (gitignore + Xcode /
// Gradle 측 *파일 존재 검증* 으로 산출물 누락을 빌드 시 fail-fast) 하에서는 의미 없는 게이트.

import { context, build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const BANNER = [
  '// QuietLounge — auto-generated by scripts/build.mjs. DO NOT EDIT.',
  '// Source: web/. Edit there and run `pnpm build`.',
  '',
].join('\n');

const TARGETS = [
  {
    name: 'chrome',
    entryPoints: [path.join(ROOT, 'web/entries/chrome.ts')],
    outfile: path.join(ROOT, 'chrome-extension/content-scripts/main.js'),
  },
  {
    name: 'safari-ext',
    entryPoints: [path.join(ROOT, 'web/entries/safari-ext.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/main.js',
    ),
  },
  {
    name: 'chrome-api-interceptor',
    entryPoints: [path.join(ROOT, 'web/entries/web-api-interceptor.ts')],
    outfile: path.join(ROOT, 'chrome-extension/content-scripts/api-interceptor.js'),
  },
  {
    name: 'safari-api-interceptor',
    entryPoints: [path.join(ROOT, 'web/entries/web-api-interceptor.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/api-interceptor.js',
    ),
  },
  {
    name: 'safari-injector',
    entryPoints: [path.join(ROOT, 'web/entries/safari-injector.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/injector.js',
    ),
  },
  {
    name: 'safari-storage-bridge',
    entryPoints: [path.join(ROOT, 'web/entries/safari-storage-bridge.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/Shared (Extension)/Resources/content-scripts/storage-bridge.js',
    ),
  },
  {
    name: 'ios-after',
    entryPoints: [path.join(ROOT, 'web/entries/ios-after.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/after.js',
    ),
  },
  {
    name: 'ios-before',
    entryPoints: [path.join(ROOT, 'web/entries/ios-before.ts')],
    outfile: path.join(
      ROOT,
      'safari-extension/QuietLounge/iOS (App)/Resources/webview-scripts/before.js',
    ),
  },
  {
    name: 'android-after',
    entryPoints: [path.join(ROOT, 'web/entries/android-after.ts')],
    outfile: path.join(ROOT, 'android-app/app/src/main/assets/webview-scripts/after.js'),
  },
  {
    name: 'android-before',
    entryPoints: [path.join(ROOT, 'web/entries/android-before.ts')],
    outfile: path.join(ROOT, 'android-app/app/src/main/assets/webview-scripts/before.js'),
  },
];

/** legacy `--check` 용 path. 현재는 산출물이 .gitignore 라 git diff 가 무의미 — 백호환 잔재. */
const ARTIFACT_PATHS = TARGETS.map((t) => path.relative(ROOT, t.outfile));

const COMMON = {
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  // 한국어 / 이모지 등 비-ASCII 문자열을 그대로 보존 — 기본은 \uXXXX escape 라
  // 산출물 grep ("클린봇", "감지") 가드와 시각적 가독성이 모두 깨진다.
  charset: 'utf8',
  // placeholder + 함수명 보존 — native bridge 와 source-level guard 테스트가 의존.
  minify: false,
  treeShaking: false,
  keepNames: true,
  legalComments: 'none',
  banner: { js: BANNER },
  loader: { '.ts': 'ts' },
  logLevel: 'info',
};

const args = new Set(process.argv.slice(2));
const watch = args.has('--watch');
const check = args.has('--check');

async function buildAll() {
  await Promise.all(
    TARGETS.map(async (t) => {
      const opts = { ...COMMON, entryPoints: t.entryPoints, outfile: t.outfile };
      await build(opts);
      console.log(`✓ ${t.name.padEnd(14)} → ${path.relative(ROOT, t.outfile)}`);
    }),
  );
}

async function watchAll() {
  const contexts = await Promise.all(
    TARGETS.map(async (t) => {
      const opts = { ...COMMON, entryPoints: t.entryPoints, outfile: t.outfile };
      const ctx = await context(opts);
      await ctx.watch();
      console.log(`👀 watching ${t.name.padEnd(11)} → ${path.relative(ROOT, t.outfile)}`);
      return ctx;
    }),
  );
  // SIGINT/SIGTERM 시 esbuild context 명시 dispose — IDE 통합 / CI 임시 watch 시
  // file watcher / worker thread 누수 방지 (Claude 50 F4).
  const shutdown = async () => {
    await Promise.all(contexts.map((c) => c.dispose()));
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

function checkDrift() {
  // 산출물이 .gitignore 인 현재 정책 하에서는 git diff 가 *항상* 빈 결과 (ignored 파일은 diff 안 잡힘)
  // → 이 함수는 *no-op* 에 가깝다. 백호환을 위해 호출은 유지하되 메시지로 명시.
  try {
    execFileSync('git', ['rev-parse', '--git-dir'], { cwd: ROOT, stdio: 'ignore' });
  } catch {
    console.log('• git 없음 — drift 검사 skip');
    return;
  }
  try {
    execFileSync('git', ['diff', '--exit-code', '--', ...ARTIFACT_PATHS], {
      cwd: ROOT,
      stdio: 'inherit',
    });
    console.log(
      '• --check: 산출물이 .gitignore 라 git diff 검사는 의미 없음 (legacy). 산출물 누락은 Xcode / Gradle 측 파일 존재 검증으로 fail-fast.',
    );
  } catch {
    console.error('✗ 산출물이 *git tracked* 상태로 변경됨 — .gitignore 잘못 설정됐거나 실수로 add 됐을 수 있습니다.');
    process.exit(1);
  }
}

if (watch) {
  await watchAll();
  // watch 는 자체 종료 안 함 — Ctrl+C 까지 idle.
} else {
  await buildAll();
  if (check) checkDrift();
}
